config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :races
  root to: "races#index"
end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :races
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @races = Race.all
  end


  def show
  end

  def new
    @race = current_user.races.build
  end


  def edit
  end

  def create
    @race = current_user.races.build(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:title, :price, :distance, :terrain, :scenic, :pb, :toilets, :changingrm, :water, :medal, :tshirt, :website, :date, :description, :area)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RaceReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do|name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :terrain %><br>
    <%= f.text_field :terrain %>
  </div>
  <div class="field">
    <%= f.label :scenic %><br>
    <%= f.text_field :scenic %>
  </div>
  <div class="field">
    <%= f.label :pb %><br>
    <%= f.text_field :pb %>
  </div>
  <div class="field">
    <%= f.label :toilets %><br>
    <%= f.check_box :toilets %>
  </div>
  <div class="field">
    <%= f.label :changingrm %><br>
    <%= f.check_box :changingrm %>
  </div>
  <div class="field">
    <%= f.label :water %><br>
    <%= f.text_field :water %>
  </div>
  <div class="field">
    <%= f.label :medal %><br>
    <%= f.text_field :medal %>
  </div>
  <div class="field">
    <%= f.label :tshirt %><br>
    <%= f.text_field :tshirt %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_area :area %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Races</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Distance</th>
      <th>Terrain</th>
      <th>Scenic</th>
      <th>Pb</th>
      <th>Toilets</th>
      <th>Changingrm</th>
      <th>Water</th>
      <th>Medal</th>
      <th>Tshirt</th>
      <th>Website</th>
      <th>Date</th>
      <th>Description</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.title %></td>
        <td><%= race.price %></td>
        <td><%= race.distance %></td>
        <td><%= race.terrain %></td>
        <td><%= race.scenic %></td>
        <td><%= race.pb %></td>
        <td><%= race.toilets %></td>
        <td><%= race.changingrm %></td>
        <td><%= race.water %></td>
        <td><%= race.medal %></td>
        <td><%= race.tshirt %></td>
        <td><%= race.website %></td>
        <td><%= race.date %></td>
        <td><%= race.description %></td>
        <td><%= race.area %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New Race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @race.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @race.price %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @race.distance %>
</p>

<p>
  <strong>Terrain:</strong>
  <%= @race.terrain %>
</p>

<p>
  <strong>Scenic:</strong>
  <%= @race.scenic %>
</p>

<p>
  <strong>Pb:</strong>
  <%= @race.pb %>
</p>

<p>
  <strong>Toilets:</strong>
  <%= @race.toilets %>
</p>

<p>
  <strong>Changingrm:</strong>
  <%= @race.changingrm %>
</p>

<p>
  <strong>Water:</strong>
  <%= @race.water %>
</p>

<p>
  <strong>Medal:</strong>
  <%= @race.medal %>
</p>

<p>
  <strong>Tshirt:</strong>
  <%= @race.tshirt %>
</p>

<p>
  <strong>Website:</strong>
  <%= @race.website %>
</p>

<p>
  <strong>Date:</strong>
  <%= @race.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @race.description %>
</p>

<p>
  <strong>Area:</strong>
  <%= @race.area %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>